eureka:
  instance:
    #instanceId: dottorzibbordi
    nonSecurePort: 8080
    preferIpAddress: false
    #hostname: 192.168.50.4
    #ipAddress: 192.168.50.4
    hostname: localhost
    ipAddress: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://137.204.35.131:8761/eureka/

anarchia:
  welcome: are you talking to me?

spring:
  rabbitmq:
    host: ${COREOS_PUBLIC_IPV4:137.204.35.131}

